name: Update Data  
on:  
  schedule:  
    - cron: '0 0 * * *'  # Daily at midnight UTC  
  workflow_dispatch:      # Manual trigger  

jobs:  
  update:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout repo  
        uses: actions/checkout@v2  
      
      - name: Fetch data  
        env:  
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}  
        run: |  
          python fetch_data.py  
      
      - name: Commit changes  
        run: |  
          git config --global user.name "GitHub Actions"  
          git config --global user.email "actions@github.com"  
          git add data/processed_data.json  
          git commit -m "Update air quality data"  
          git push  